export const AIRPORT_TZ: Record<string, string> = {
  'ICN': 'Asia/Seoul', 'GMP': 'Asia/Seoul', 'PUS': 'Asia/Seoul', 'CJU': 'Asia/Seoul',
  'NRT': 'Asia/Tokyo', 'HND': 'Asia/Tokyo', 'KIX': 'Asia/Tokyo', 'NGO': 'Asia/Tokyo', 'FUK': 'Asia/Tokyo', 'CTS': 'Asia/Tokyo',
  'PEK': 'Asia/Shanghai', 'PVG': 'Asia/Shanghai', 'CAN': 'Asia/Shanghai', 'SZX': 'Asia/Shanghai', 'HKG': 'Asia/Hong_Kong',
  'TPE': 'Asia/Taipei', 'MNL': 'Asia/Manila', 'SIN': 'Asia/Singapore', 'KUL': 'Asia/Kuala_Lumpur', 'BKK': 'Asia/Bangkok',
  'SGN': 'Asia/Ho_Chi_Minh', 'HAN': 'Asia/Bangkok', 'DPS': 'Asia/Makassar', 'CGK': 'Asia/Jakarta',
  'GUM': 'Pacific/Guam', 'SYD': 'Australia/Sydney', 'BNE': 'Australia/Brisbane', 'AKL': 'Pacific/Auckland',
  'DEL': 'Asia/Kolkata', 'BOM': 'Asia/Kolkata', 'MLE': 'Indian/Maldives', 'DXB': 'Asia/Dubai', 'IST': 'Europe/Istanbul',
  'LAX': 'America/Los_Angeles', 'SFO': 'America/Los_Angeles', 'SEA': 'America/Los_Angeles', 'LAS': 'America/Los_Angeles', 
  'YVR': 'America/Vancouver', 'ANC': 'America/Anchorage', 'HNL': 'Pacific/Honolulu',
  'JFK': 'America/New_York', 'BOS': 'America/New_York', 'ATL': 'America/New_York', 'IAD': 'America/New_York', 
  'YYZ': 'America/Toronto', 'DTW': 'America/Detroit', 'ORD': 'America/Chicago', 'DFW': 'America/Chicago', 'MIA': 'America/New_York',
  'GDL': 'America/Mexico_City',
  'SCL': 'America/Santiago', 'LHR': 'Europe/London', 'CDG': 'Europe/Paris', 'FRA': 'Europe/Berlin', 'FCO': 'Europe/Rome', 
  'MXP': 'Europe/Rome', 'AMS': 'Europe/Amsterdam', 'ZRH': 'Europe/Zurich', 'VIE': 'Europe/Vienna', 
  'PRG': 'Europe/Prague', 'BUD': 'Europe/Budapest', 'MAD': 'Europe/Madrid', 'BCN': 'Europe/Madrid',
  'LIS': 'Europe/Lisbon', 'ZAG': 'Europe/Zagreb', 'VVO': 'Asia/Vladivostok', 'TAS': 'Asia/Tashkent', 'ALA': 'Asia/Almaty'
};

export const KOREA_PORTS = ['ICN', 'GMP', 'PUS', 'CJU', 'TAE', 'KWJ', 'RSU', 'USN', 'KUV', 'WJU', 'YNY'];

export const PER_DIEM_RATES: Record<string, number> = {
  "SFO": 4.21, "LAX": 4.01, "LAS": 4.01, "ANC": 3.81, "SEA": 3.81, "ATL": 3.61, "BOS": 3.61, "JFK": 3.61, "ORD": 3.41, "HNL": 3.41,
  "DFW": 3.21, "MIA": 3.21, "LCK": 3.21, "IAD": 3.01, "SCL": 3.19, "YVR": 3.19, "YYZ": 3.00, "ZRH": 4.16, "LHR": 3.86, "FCO": 3.71,
  "FRA": 3.41, "VIE": 3.41, "CDG": 3.26, "AMS": 3.26, "MXP": 3.26, "MAD": 3.26, "BCN": 3.11, "IST": 3.01, "SIN": 2.96, "BKK": 2.80,
  "DEL": 2.50, "BOM": 2.50, "MLE": 2.50, "KUL": 2.32, "SGN": 2.32, "GUM": 3.28, "HKG": 2.35, "TPE": 2.20, "MFM": 2.20, "ULN": 1.95, "DXB": 2.59
};

export const EURO_CITIES = [
  "LHR", "CDG", "FRA", "FCO", "MXP", "ZRH", "VIE", "PRG", "BUD", "MAD", "BCN", "AMS", "IST", "LIS", "ZAG",
  "VVO", "TAS", "ALA", "SVO", "LED"
];

export const SIM_KEYWORDS = ["RECPT", "RECPC", "UPRT"];

export const HOTELS: Record<string, string> = {
  "USN": "롯데시티호텔 울산",
  "TAE": "인터불고 (대구광역시 수성구 만촌동 300 번지)",
  "CJU": "리젠트 마린 (제주시 건입동 서부두 2길 20)",
  "PUS": "Hotel NongSim (부산시 동래구 금강공원로20번길 23)",
  "NRT": "HOTEL MYSTAYS PREMIER Narita (31 OYAMA, NARITA-SHI, CHIBA 286-0131, JAPAN)",
  "CTS": "ANA CROWNE PLAZA HOTEL (2-2-1 Hokuei chitose Hokkaido 066-0036)",
  "HND": "JAL CITY HANEDA (4-11 Haneda Asahi-cho, Ota-ku, Tokyo 144-0042)",
  "NGO": "J. HOTEL RINKU (3-2-1. Rinku. Tokoname. Aichi. 479-0882. Japan)",
  "KIX": "Washington Hotel Kansai Airport (1-7 Rinku Orai-kita Izumisano-shi Osaka 598-8522 Japan)",
  "PVG": "Ramada Plaza / InterContinental (No.1100 Qi Hang Road, Pudong, Shanghai)",
  "MFM": "Crowne Plaza Macau (The Residencia, Tower 7, Macau)",
  "KMG": "Doubletree by Hilton Kunming Airport (No.12001-1, Airport Road Guandu District, Kunming)",
  "HKG": "Four Points by Sheraton HOTEL (9 Yi Tung Road, Tung Chung, Lantau Island)",
  "UBN": "CHINGGIS KHAAN HOTEL (Tokyo street 5, Ulaanbaatar 49, Mongolia)",
  "DAD": "Grand Mercure Danang (Lot A1 Zone of Green Island, Hoa Cuong Bac Hai Chau District Danang, Vietnam)",
  "KUL": "Sheraton Imperial Hotel Kuala Lumpur (Jln Sultan Ismail, Chow Kit, 50250 Kuala Lumpur)",
  "PEN": "Evergreen Laurel Hotel (53, Persiaran, Gurney, 10250, Penang)",
  "BKK": "THE SUKOSOL BANGKOK HOTEL (477 Si Ayuthaya Road, Phaya Thai, Bangkok 10400)",
  "HKT": "Wyndham Garden Naithon Phuket (28/40 Naithon Beach Sakhu, Thalang District, Phuket)",
  "SGN": "Hotel Nikko Saigon (235, Nguyễn Văn Cừ, Phường Nguyễn Cư Trinh, Quận 1)",
  "PQC": "Best Western Premier Sonasea Phu Quoc (Duong Bao Area, Phu Quoc Special Zone, An Giang Province)",
  "MNL": "Dusit Thani Hotel Manila (1223 Epifanio de los Santos Ave. Makati, 12242 Metro Manila)",
  "CXR": "Intercontinental Nha Trang (32-34 Tran Phu Street, Nha Trang City)",
  "KTI": "Sokha Phnom Penh Hotel (Street Keochenda, Phum I, Sangkat Chory Changvar, Khan Chroy Changvar, Phnom Penh)",
  "DPS": "Grand Mercure Bali Seminyak (Jalan Arjuna No. 40 Seminyak, Kecamatan Kuta, Badung)",
  "HAN": "Novotel Hanoi Thai Ha Hotel (No. 2 Thai Ha Street, Dong Da District, Hanoi)",
  "CNX": "Novotel Chiangmai Nimman Journeyhub (7*77 Moo 2, Huay Kaew Rd, Soi Sreesud, Chang Phueak, 50300)",
  "CEB": "Radisson Blu Hotel, Cebu (Serging Osmena Boulevard, Corner Pope John Paul II Ave, Cebu City)",
  "SIN": "Amara Singapore (165 Tanjong Pagar Road, Singapore 088539)",
  "CGK": "Novotel Tangerang (Tangcity superblock, Jl. jend sudirman no. 1)",
  "DEL": "The Grand New Delhi (Nelson Mandela Marg, Pocket 4, Vasant Kunj, New Delhi)",
  "TLV": "Publica Isrotel (ABBA Eban Blvd 9, Herzliya, Israel)",
  "KTM": "Hilton Kathmandu Hotel",
  "DXB": "Marriott Al Jaddaf Dubai (Oud Metha Road, Al Jaddaf Area, Dubai)",
  "BOS": "Homewood Suites by Hilton Boston Logan (145 Beech Street, Chelsea, Massachusetts)",
  "HNL": "Sheraton Princess Kaiulani (120 Kaiulani Ave, Honolulu, Hawaii)",
  "MIA": "Intercontinental at Doral Miami Hotel (2505 NW 87th Avenue, Doral, FL)",
  "YVR": "Marriott / Sheraton Vancouver Airport Hotel (7571 Westminster Hwy, Richmond, BC)",
  "JFK": "HYATT PLACE MIDTOWN-SOUTH (52 W 36th St, New York, NY 10018)",
  "LAS": "Trump International Las Vegas (2000 Fashion Show Drive Las Vegas)",
  "SFO": "Hyatt Regency San Francisco Airport Hotel (1333 Bayshore Highway, Burlingame, CA)",
  "ORD": "Wyndham Chicago O'Hare (1450 Touhy Avenue, Des Plaines, Illinois)",
  "YYZ": "Chelsea Hotel Toronto (33 Gerrard Street West, Toronto, ON)",
  "IAD": "The Westin Tysons Corner (7801 Leesburg Pike, Falls Church, VA)",
  "SEA": "Seattle Airport Marriott (3201 South 176th Street, Seattle, Washington)",
  "LAX": "InterContinental Los Angeles Downtown (935 West 7th St. Los Angeles, California)",
  "DFW": "Hilton Dallas Lincoln Centre (5410 LBJ Freeway, Dallas, TX)",
  "ATL": "The Westin Peachtree Plaza (210 Peachtree St. NW, Atlanta, GA)",
  "ANC": "Crowne Plaza Anchorage Midtown (109 W International Airport Rd, Anchorage, AK)",
  "OSL": "Radisson RED Oslo Airport (Henrik lbsens veg (A), Gardermoen)",
  "ATH": "Sofitel Athens Airport (Athens International Airport, 19019 ATHENS SPATA)",
  "VIE": "NH hotel Airport Vienna (Flughafen Wien A. 1300 Vienna)",
  "DBV": "Hotel Adria Dubrovnik (Radnička ulica 46, 20000, Dubrovnik)",
  "PRG": "Courtyard by Marriott Prague Airport (Aviaticka 1092/8, Prague, 161 00)",
  "MAD": "Hotel Marriott Auditorium (400 Avda De Aragon 28022 Madrid)",
  "MXP": "Doubletree by Hilton Milan Malpensa Solbiate Olona (Via per Busto Arsizio, 7, 21058 Solbiate Olona VA)",
  "CDG": "The Atrium Hotel & Conference Centre, Paris CDG Airport by Penta (351 Avenue du Bois de la pie . BP 40048 . Paris Nord Ⅱ. 95912 Roissy CDG Cedex)",
  "LIS": "Holiday Inn Lisbon-Continental (Rua Laura Alves, 9 1069-169 Lisboa)",
  "BCN": "Ilunion Barcelona (Calle Ramon Turró 196/198 08005 Barcelona)",
  "BUD": "Mercure Budapest Korona Hotel (Kecskemeti utca 14 NTAK: SZ19000369, szálloda 1053)",
  "IST": "Sheraton Istanbul Levent (Büyükdere Cd. No:3-4, 4 Levent, Kağıthane, İstanbul, Türkiye)",
  "ZRH": "HILTON Zürich Airport Hotel (Hohenbuehlstrasse 10, 8152 Opfikon)",
  "FRA": "Sheraton Frankfurt Airport Hotel (Hugo-Eckener-Ring 15, Flughafen/Terminal 1, Frankfurt am Main)",
  "AMS": "Steigenberger Airport Hotel (Stationsplein ZW 951, 1117 CE, Amsterdam Schiphol-Oost)",
  "LHR": "HOLIDAY INN EXPRESS T4 ((Terminal 4) 공항 청사와 연결된 통로)",
  "AKL": "Grand Millennium Hotel Auckland (71 Mayoral Drive, Cnr Vincent Street, Auckland 1010)",
  "GUM": "Hilton Guam Resort & Spa (202 Hilton Road Tumon Bay, Guam 96913)",
  "BNE": "Grand Chancellor Brisbane (23 Leichhardt st (Cnr Wickham Terrace) Brisbane)",
  "SYD": "Rydges World Square Sydney (389 Pitt Street, Sydney, NSW, 2000)",
  "SCL": "InterContinental Santiago Hotel (Av Vitacura 2885, Las Condes, Region Metropolitana, Chile)",
  "TAS": "Lotte City Hotel Tashkent Palace (56 Buyuk Turon Street, Tashkent, Uzbekistan)"
};
