import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { google } from "googleapis";

export async function POST(req: Request) {
  const session: any = await auth();
  if (!session || !session.user || !session.accessToken) {
    return NextResponse.json({ error: "Unauthorized or missing access token" }, { status: 401 });
  }

  try {
    const { events, calendarId = "primary" } = await req.json();
    if (!events || !Array.isArray(events)) {
      return NextResponse.json({ error: "Invalid events payload" }, { status: 400 });
    }

    const oauth2Client = new google.auth.OAuth2();
    oauth2Client.setCredentials({ access_token: session.accessToken });
    const calendar = google.calendar({ version: "v3", auth: oauth2Client });

    let deletedCount = 0;
    if (events.length > 0) {
      // 1. Determine target month (the month that contains the most events)
      const monthCounts: Record<string, number> = {};
      events.forEach((ev: any) => {
        const d = new Date(ev.start.dateTime || ev.start.date);
        const key = `${d.getUTCFullYear()}-${d.getUTCMonth()}`;
        monthCounts[key] = (monthCounts[key] || 0) + 1;
      });
      const targetMonthKey = Object.keys(monthCounts).sort((a, b) => monthCounts[b] - monthCounts[a])[0];
      const [tYear, tMonth] = targetMonthKey.split('-').map(Number);

      // 2. Define clear boundaries for that month
      const timeMin = new Date(tYear, tMonth, 1).toISOString();
      const timeMax = new Date(tYear, tMonth + 1, 0, 23, 59, 59, 999).toISOString();

      // 3. Fetch existing events in that month
      const existingRes = await calendar.events.list({
        calendarId,
        timeMin,
        timeMax,
        singleEvents: true,
      });

      // 4. Filter only events generated by our app
      const existingEvents = existingRes.data.items || [];
      const eventsToDelete = existingEvents.filter(ev =>
        ev.extendedProperties?.private?.source === 'kalroster'
      );

      // 5. Delete old events
      for (const ev of eventsToDelete) {
        if (ev.id) {
          await calendar.events.delete({ calendarId, eventId: ev.id });
          deletedCount++;
        }
      }
    }

    let insertedCount = 0;
    for (const ev of events) {
      // Copy to avoid mutating the original request payload
      const cleanEv = { ...ev };
      delete cleanEv.type;
      cleanEv.extendedProperties = { private: { source: 'kalroster' } };
      
      await calendar.events.insert({ calendarId, requestBody: cleanEv });
      insertedCount++;
    }

    return NextResponse.json({ success: true, message: `Updated target month: Deleted ${deletedCount} old events, and synced ${insertedCount} new events!` });
  } catch (error) {
    console.error("Calendar sync error:", error);
    return NextResponse.json({ error: "Calendar sync failed" }, { status: 500 });
  }
}
